version: '3'

services:
  se-server:
    # image: mmmaxwwwell/space-engineers-dedicated-docker-linux:latest
    build: .
    container_name: space-engineers-dedicated-docker-linux
    restart: "no"
    ports:
     - "27016:27016/udp"
