version: '3'

services:
  se-server:
    #build: .
    image: mmmaxwwwell/space-engineers-dedicated-docker-linux:latest
    container_name: se-ds-docker-debian
    restart: unless-stopped
    volumes:
      - /appdata/space-engineers/World:/appdata/space-engineers/World
      - /appdata/space-engineers/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated
      - /appdata/space-engineers/steamcmd:/root/.steam
      - /appdata/space-engineers/SpaceEngineers-Dedicated.cfg:/appdata/space-engineers/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg
    stdin_open: true 
    tty: true
    # network_mode: host
    ports:
     - "27016:27016/udp"
